name: txtr_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: 3.10.5 # for now this is a comment on what version of flutter is recommended

dependencies:
  background_sms:
  device_info_plus: ^10.0.1
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.5
  flutter_bloc: ^8.1.3
  flutter_contacts: ^1.1.6
  flutter_form_builder: ^9.0.0
  flutter_local_notifications: ^17.0.0
  flutter_localizations:
    sdk: flutter
  flutter_sms_inbox: ^1.0.3
  form_builder_validators: ^9.0.0
  network_info_plus: ^5.0.2
  path_provider: ^2.1.0
  permission_handler: ^11.3.1
  shelf_router: ^1.1.4
  sqlcipher_flutter_libs: ^0.6.1
  sqlite3: ^2.1.0
  txtr_shared:
    path: ../txtr_shared
  uuid: ^4.3.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/ssl/

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/txtr_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
