name: txtr_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: 3.10.5 # for now this is a comment on what version of flutter is recommended

dependencies:
  device_info_plus: ^9.0.2
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_background_service: ^3.0.1
  flutter_bloc: ^8.1.3
  flutter_contacts: ^1.1.6
  flutter_form_builder: ^9.0.0
  flutter_local_notifications: ^15.0.1
  flutter_localizations:
    sdk: flutter
  flutter_sms:
    git:
      url: git@github.com:RickPoleshuck/flutter_sms.git
  flutter_sms_inbox: ^1.0.3
  form_builder_validators: ^9.0.0
  network_info_plus: ^4.0.1
  path_provider: ^2.1.0
  permission_handler: ^10.3.0
  shelf_router: ^1.1.4
  sqlcipher_flutter_libs: ^0.5.7
  sqlite3: ^2.1.0
  txtr_shared:
    path: ../txtr_shared
  uuid: ^3.0.7
  wifi_info_flutter: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/ssl/
