name: txtr_dsk
description: txtr client

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: 3.10.5 # for now this is a comment on what version of flutter is recommended

dependencies:
  dio: ^5.2.1+1
  equatable: ^2.0.5
  intl: ^0.18.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  form_builder_validators: ^9.0.0
  flutter_form_builder: ^9.0.0
  flutter_localizations:
    sdk: flutter
  network_info_plus: ^4.0.1
  network_tools: ^3.2.1
  shared_preferences: ^2.1.2
  txtr_shared:
    path: ../txtr_shared
  window_manager: ^0.3.5
  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.12


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
