name: txtr
version: '1.0'
summary: Desktop SMS Application
description: Secure desktop SMS application that connects to mobile phones

base: core22
confinement: strict
grade: stable

apps:
  txtr:
    command: txtr_dsk
    extensions: [gnome]
    plugs:
    - network

parts:
  txtr:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
