name: txtr
version: '1.0.0'
summary: Desktop SMS Application
description: Secure desktop SMS application that connects to mobile phones
#
# sudo snap install ./txtr_1.0.0_amd64.snap  --dangerous --devmode
#

base: core22
confinement: devmode
grade: stable

apps:
  txtr:
    command: txtr_dsk
    extensions: [gnome]
    plugs:
    - network

parts:
  txtr:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
